modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="Aeronautics: Big"
    authors="axialeaa, CallMeEcho, Kilip1000"
    description='''Adds composite materials for building large-scale aircraft in Create: Aeronautics!'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simulated"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="aeronautics"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="offroad"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
